env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
  - "plugin:prettier/recommended"
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
rules:
  require-jsdoc: off
  new-cap: off
  prettier/prettier:
    - error
    - singleQuote: true
